#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${blade.datasource.dev.url}
#    username: ${blade.datasource.dev.username}
#    password: ${blade.datasource.dev.password}
    url: jdbc:mysql://hadoop01:3306/blade?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
  cloud:
    nacos:
      config:
        server-addr: hadoop02:8848
      discovery:
        server-addr: hadoop02:8848
      sentinel:
        transport:
          dashboard: hadoop02:8858


#第三方登陆
social:
  enabled: true
  domain: http://hadoop02:1888
