#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
  cloud:
    nacos:
      config:
        server-addr: hadoop02:8848
      discovery:
        server-addr: hadoop02:8848
      sentinel:
        transport:
          dashboard: hadoop02:8858


#第三方登陆
social:
  enabled: true
  domain: http://hadoop02:1888
